import type { ProviderSpec } from '../types';

export const providers: readonly ProviderSpec[] = [
  {
    id: 'xai',
    label: 'xAI Grok Imagine',
    wave: 1,
    transport: 'proxy',
    hosts: ['api.x.ai'],
    auth: { header: 'Authorization', scheme: 'Bearer', help: 'xAI API key from console.x.ai' },
    outputHosts: ['imgen.x.ai'],
    inputModes: ['base64'],
    outputExpiry: '24h',
    docsPath: 'docs/providers/xai.md',
  },
  {
    id: 'fal',
    label: 'fal.ai',
    wave: 1,
    transport: 'proxy',
    hosts: ['queue.fal.run', 'fal.run', 'rest.fal.ai', 'api.fal.ai'],
    auth: { header: 'Authorization', scheme: 'Key', help: 'fal.ai key in id:secret format from fal.ai/dashboard/keys' },
    outputHosts: ['fal.media', '*.fal.media'],
    inputModes: ['url', 'base64', 'own-upload'],
    outputExpiry: undefined,
    docsPath: 'docs/providers/fal.md',
  },
  {
    id: 'google',
    label: 'Google Gemini',
    wave: 1,
    transport: 'direct',
    hosts: ['generativelanguage.googleapis.com'],
    auth: { header: 'x-goog-api-key', scheme: 'raw', help: 'Google API key from aistudio.google.com' },
    outputHosts: ['generativelanguage.googleapis.com'],
    inputModes: ['base64'],
    outputExpiry: '48h',
    docsPath: 'docs/providers/google.md',
  },
  {
    id: 'openai',
    label: 'OpenAI',
    wave: 1,
    transport: 'proxy',
    hosts: ['api.openai.com'],
    auth: { header: 'Authorization', scheme: 'Bearer', help: 'OpenAI API key from platform.openai.com' },
    outputHosts: ['oaidalleapiprodscus.blob.core.windows.net'],
    inputModes: ['base64'],
    outputExpiry: undefined,
    docsPath: 'docs/providers/openai.md',
  },
  {
    id: 'replicate',
    label: 'Replicate',
    wave: 1,
    transport: 'proxy',
    hosts: ['api.replicate.com'],
    auth: { header: 'Authorization', scheme: 'Bearer', help: 'Replicate API token from replicate.com/account/api-tokens' },
    outputHosts: ['replicate.delivery', '*.replicate.delivery'],
    inputModes: ['base64', 'url'],
    outputExpiry: '1h',
    docsPath: 'docs/providers/replicate.md',
  },
  {
    id: 'cf-workers-ai',
    label: 'Cloudflare Workers AI',
    wave: 1,
    transport: 'proxy',
    hosts: ['api.cloudflare.com'],
    auth: { header: 'Authorization', scheme: 'Bearer', help: 'Cloudflare API token with Workers AI permissions' },
    outputHosts: [], // returns bytes directly
    inputModes: ['base64'],
    outputExpiry: undefined,
    docsPath: 'docs/providers/cloudflare-workers-ai.md',
  },
  {
    id: 'byteplus-ark',
    label: 'BytePlus ModelArk',
    wave: 2,
    transport: 'proxy',
    hosts: ['ark.ap-southeast.bytepluses.com', 'ark.cn-beijing.volces.com'],
    auth: { header: 'Authorization', scheme: 'Bearer', help: 'BytePlus API key from console.byteplus.com' },
    outputHosts: ['*.byteimg.com'], // unverified
    inputModes: ['base64', 'url'],
    outputExpiry: '24h',
    docsPath: 'docs/providers/byteplus-ark.md',
  },
  {
    id: 'venice',
    label: 'Venice.ai',
    wave: 2,
    transport: 'proxy',
    hosts: ['api.venice.ai'],
    auth: { header: 'Authorization', scheme: 'Bearer', help: 'Venice API key from venice.ai/settings/api' },
    outputHosts: [], // returns base64
    inputModes: ['base64', 'url'],
    outputExpiry: undefined,
    docsPath: 'docs/providers/venice.md',
  },
  {
    id: 'kling',
    label: 'Kling',
    wave: 2,
    transport: 'proxy',
    hosts: ['api-singapore.klingai.com', 'api.klingai.com', 'api-beijing.klingai.com'],
    auth: { header: 'Authorization', scheme: 'jwt-hs256', help: 'Kling access_key:secret_key pair from klingai.com console' },
    outputHosts: ['*.klingai.com'], // unverified
    inputModes: ['base64', 'url'],
    outputExpiry: undefined,
    docsPath: 'docs/providers/kling.md',
  },
  {
    id: 'stability',
    label: 'Stability AI',
    wave: 2,
    transport: 'proxy',
    hosts: ['api.stability.ai'],
    auth: { header: 'Authorization', scheme: 'Bearer', help: 'Stability AI API key from platform.stability.ai' },
    outputHosts: [], // returns bytes directly
    inputModes: ['multipart'],
    outputExpiry: undefined,
    docsPath: 'docs/providers/stability.md',
  },
  {
    id: 'bfl',
    label: 'Black Forest Labs',
    wave: 2,
    transport: 'proxy',
    hosts: ['api.bfl.ai', 'api.eu.bfl.ai', 'api.us.bfl.ai'],
    auth: { header: 'x-key', scheme: 'raw', help: 'BFL API key from api.bfl.ai' },
    outputHosts: ['bfldeliveryprod.blob.core.windows.net'],
    inputModes: ['base64', 'url'],
    outputExpiry: '10m',
    docsPath: 'docs/providers/bfl.md',
  },
  {
    id: 'hf-inference',
    label: 'Hugging Face Inference',
    wave: 2,
    transport: 'proxy',
    hosts: ['router.huggingface.co'],
    auth: { header: 'Authorization', scheme: 'Bearer', help: 'Hugging Face access token from huggingface.co/settings/tokens' },
    outputHosts: ['*.huggingface.co'], // unverified; returns bytes for some backends
    inputModes: ['base64'],
    outputExpiry: undefined,
    docsPath: 'docs/providers/huggingface-inference.md',
  },
  {
    id: 'hf-space',
    label: 'Hugging Face Spaces',
    wave: 2,
    transport: 'direct',
    hosts: ['*.hf.space'],
    auth: { header: 'Authorization', scheme: 'Bearer', help: 'Hugging Face access token (optional for public Spaces)' },
    outputHosts: ['*.hf.space'],
    inputModes: ['base64', 'url'],
    outputExpiry: undefined,
    docsPath: 'docs/providers/huggingface-spaces.md',
  },
  {
    id: 'runpod',
    label: 'RunPod',
    wave: 2,
    transport: 'proxy',
    hosts: ['api.runpod.ai'],
    auth: { header: 'Authorization', scheme: 'Bearer', help: 'RunPod API key from runpod.io/console/user/settings' },
    outputHosts: ['image.runpod.ai'],
    inputModes: ['base64', 'url'],
    outputExpiry: '7d',
    docsPath: 'docs/providers/runpod.md',
  },
  {
    id: 'minimax',
    label: 'MiniMax',
    wave: 3,
    transport: 'proxy',
    hosts: ['api.minimax.io', 'api.minimaxi.com'],
    auth: { header: 'Authorization', scheme: 'Bearer', help: 'MiniMax API key from platform.minimax.io' },
    outputHosts: ['*.minimaxi.com'], // unverified
    inputModes: ['base64', 'url'],
    outputExpiry: undefined,
    docsPath: 'docs/providers/minimax.md',
  },
  {
    id: 'runway',
    label: 'Runway',
    wave: 3,
    transport: 'proxy',
    hosts: ['api.dev.runwayml.com'],
    auth: {
      header: 'Authorization',
      scheme: 'Bearer',
      extraHeaders: { 'X-Runway-Version': '2024-11-06' },
      help: 'Runway API secret from dev.runwayml.com',
    },
    outputHosts: ['*.runwayml.com'], // unverified
    inputModes: ['base64', 'url', 'own-upload'],
    outputExpiry: undefined,
    docsPath: 'docs/providers/runway.md',
  },
  {
    id: 'luma',
    label: 'Luma Dream Machine',
    wave: 3,
    transport: 'proxy',
    hosts: ['api.lumalabs.ai'],
    auth: { header: 'Authorization', scheme: 'Bearer', help: 'Luma API key from lumalabs.ai/api' },
    outputHosts: ['*.lumalabs.ai'], // unverified
    inputModes: ['url'],
    outputExpiry: undefined,
    docsPath: 'docs/providers/luma.md',
  },
  {
    id: 'ideogram',
    label: 'Ideogram',
    wave: 3,
    transport: 'proxy',
    hosts: ['api.ideogram.ai'],
    auth: { header: 'Api-Key', scheme: 'raw', help: 'Ideogram API key from ideogram.ai/manage-api' },
    outputHosts: ['ideogram.ai'],
    inputModes: ['multipart'],
    outputExpiry: '1h',
    docsPath: 'docs/providers/ideogram.md',
  },
  {
    id: 'recraft',
    label: 'Recraft',
    wave: 3,
    transport: 'proxy',
    hosts: ['external.api.recraft.ai'],
    auth: { header: 'Authorization', scheme: 'Bearer', help: 'Recraft API key from recraft.ai' },
    outputHosts: ['img.recraft.ai'],
    inputModes: ['base64', 'url'],
    outputExpiry: '24h',
    docsPath: 'docs/providers/recraft.md',
  },
  {
    id: 'leonardo',
    label: 'Leonardo.Ai',
    wave: 3,
    transport: 'proxy',
    hosts: ['cloud.leonardo.ai'],
    auth: { header: 'Authorization', scheme: 'Bearer', help: 'Leonardo API key from app.leonardo.ai/api-access' },
    outputHosts: ['cdn.leonardo.ai'],
    inputModes: ['own-upload'],
    outputExpiry: undefined,
    docsPath: 'docs/providers/leonardo.md',
  },
  {
    id: 'wavespeed',
    label: 'WaveSpeed AI',
    wave: 3,
    transport: 'proxy',
    hosts: ['api.wavespeed.ai'],
    auth: { header: 'Authorization', scheme: 'Bearer', help: 'WaveSpeed API key from wavespeed.ai' },
    outputHosts: ['*.wavespeed.ai'], // unverified
    inputModes: ['base64', 'url'],
    outputExpiry: '7d',
    docsPath: 'docs/providers/wavespeed.md',
  },
  {
    id: 'together',
    label: 'Together AI',
    wave: 3,
    transport: 'proxy',
    hosts: ['api.together.xyz', 'api.together.ai'],
    auth: { header: 'Authorization', scheme: 'Bearer', help: 'Together API key from api.together.ai/settings/api-keys' },
    outputHosts: ['api.together.xyz', 'api.together.ai'], // unverified
    inputModes: ['base64', 'url'],
    outputExpiry: undefined,
    docsPath: 'docs/providers/together.md',
  },
  {
    id: 'fireworks',
    label: 'Fireworks AI',
    wave: 3,
    transport: 'proxy',
    hosts: ['api.fireworks.ai'],
    auth: { header: 'Authorization', scheme: 'Bearer', help: 'Fireworks API key from fireworks.ai' },
    outputHosts: ['*.fireworks.ai'], // unverified; sync returns bytes, async returns URLs
    inputModes: ['base64'],
    outputExpiry: undefined,
    docsPath: 'docs/providers/together.md',
  },
  {
    id: 'openai-compat',
    label: 'OpenAI-Compatible',
    wave: 2,
    transport: 'local',
    hosts: [],
    auth: { header: 'Authorization', scheme: 'Bearer', help: 'API key for the OpenAI-compatible endpoint' },
    outputHosts: [],
    inputModes: ['base64'],
    outputExpiry: undefined,
    docsPath: 'docs/providers/together.md',
  },
  {
    id: 'comfyui',
    label: 'ComfyUI',
    wave: 1,
    transport: 'local',
    hosts: [],
    auth: { header: 'Authorization', scheme: 'Bearer', help: 'No auth needed for local; tunnel uses Access service token' },
    outputHosts: [],
    inputModes: ['base64', 'own-upload'],
    outputExpiry: undefined,
    docsPath: 'docs/providers/comfyui.md',
  },
  {
    id: 'a1111',
    label: 'AUTOMATIC1111 / Forge',
    wave: 2,
    transport: 'local',
    hosts: [],
    auth: { header: 'Authorization', scheme: 'Bearer', help: 'Optional HTTP Basic auth if --api-auth is set' },
    outputHosts: [],
    inputModes: ['base64'],
    outputExpiry: undefined,
    docsPath: 'docs/providers/a1111-forge.md',
  },
  {
    id: 'swarmui',
    label: 'SwarmUI',
    wave: 3,
    transport: 'local',
    hosts: [],
    auth: { header: 'Authorization', scheme: 'Bearer', help: 'SwarmUI session auth via cookie' },
    outputHosts: [],
    inputModes: ['base64'],
    outputExpiry: undefined,
    docsPath: 'docs/providers/swarmui-invoke.md',
  },
] as const;

const byId = new Map(providers.map((p) => [p.id, p]));

export function getProvider(id: string): ProviderSpec | undefined {
  return byId.get(id);
}

export function getAllProviderIds(): string[] {
  return providers.map((p) => p.id);
}

export function getProxyHosts(): Map<string, string[]> {
  const m = new Map<string, string[]>();
  for (const p of providers) {
    if (p.hosts.length > 0) m.set(p.id, p.hosts);
  }
  return m;
}

export function getAllOutputHosts(): string[] {
  const s = new Set<string>();
  for (const p of providers) for (const h of p.outputHosts) s.add(h);
  return [...s];
}
