import type { ModelSpec } from '@shared/types';

/** Curated fal.ai model catalogue. */
export const falModels: ModelSpec[] = [
  // ── Image: FLUX ───────────────────────────────────────────────────
  {
    id: 'fal-ai/flux/schnell',
    provider_id: 'fal',
    label: 'FLUX.1 Schnell',
    description: 'Fast FLUX text-to-image (4 steps)',
    capabilities: ['text2image'],
    params: {
      prompt: { type: 'string', label: 'Prompt', required: true, multiline: true },
      image_size: {
        type: 'enum',
        label: 'Image Size',
        enum: ['square_hd', 'square', 'portrait_4_3', 'portrait_16_9', 'landscape_4_3', 'landscape_16_9'],
        options: [
          { value: 'square_hd', label: 'Square HD (1024x1024)' },
          { value: 'square', label: 'Square (512x512)' },
          { value: 'portrait_4_3', label: 'Portrait 4:3' },
          { value: 'portrait_16_9', label: 'Portrait 16:9' },
          { value: 'landscape_4_3', label: 'Landscape 4:3' },
          { value: 'landscape_16_9', label: 'Landscape 16:9' },
        ],
        default: 'landscape_4_3',
      },
      num_inference_steps: { type: 'integer', label: 'Steps', default: 4, min: 1, max: 12, advanced: true },
      seed: { type: 'integer', label: 'Seed', advanced: true },
      num_images: { type: 'integer', label: 'Number of Images', default: 1, min: 1, max: 4 },
      enable_safety_checker: { type: 'boolean', label: 'Safety Checker', default: true, advanced: true },
    },
    priceHint: '~$0.003 / image',
  },
  {
    id: 'fal-ai/flux/dev',
    provider_id: 'fal',
    label: 'FLUX.1 Dev',
    description: 'High-quality FLUX text-to-image and image-to-image',
    capabilities: ['text2image', 'image2image'],
    params: {
      prompt: { type: 'string', label: 'Prompt', required: true, multiline: true },
      image_url: { type: 'image', label: 'Input Image', help: 'Optional reference image for image-to-image', showWhen: { field: '__capability', value: 'image2image' } },
      strength: { type: 'number', label: 'Strength', default: 0.8, min: 0, max: 1, step: 0.05, showWhen: { field: '__capability', value: 'image2image' } },
      image_size: {
        type: 'enum',
        label: 'Image Size',
        enum: ['square_hd', 'square', 'portrait_4_3', 'portrait_16_9', 'landscape_4_3', 'landscape_16_9'],
        options: [
          { value: 'square_hd', label: 'Square HD (1024x1024)' },
          { value: 'square', label: 'Square (512x512)' },
          { value: 'portrait_4_3', label: 'Portrait 4:3' },
          { value: 'portrait_16_9', label: 'Portrait 16:9' },
          { value: 'landscape_4_3', label: 'Landscape 4:3' },
          { value: 'landscape_16_9', label: 'Landscape 16:9' },
        ],
        default: 'landscape_4_3',
      },
      num_inference_steps: { type: 'integer', label: 'Steps', default: 28, min: 1, max: 50, advanced: true },
      guidance_scale: { type: 'number', label: 'Guidance Scale', default: 3.5, min: 1, max: 20, step: 0.5, advanced: true },
      seed: { type: 'integer', label: 'Seed', advanced: true },
      num_images: { type: 'integer', label: 'Number of Images', default: 1, min: 1, max: 4 },
      enable_safety_checker: { type: 'boolean', label: 'Safety Checker', default: true, advanced: true },
    },
    priceHint: '~$0.025 / image',
  },
  {
    id: 'fal-ai/flux-pro/v1.1',
    provider_id: 'fal',
    label: 'FLUX Pro v1.1',
    description: 'Professional FLUX model with superior quality',
    capabilities: ['text2image'],
    params: {
      prompt: { type: 'string', label: 'Prompt', required: true, multiline: true },
      image_size: {
        type: 'enum',
        label: 'Image Size',
        enum: ['square_hd', 'square', 'portrait_4_3', 'portrait_16_9', 'landscape_4_3', 'landscape_16_9'],
        options: [
          { value: 'square_hd', label: 'Square HD (1024x1024)' },
          { value: 'square', label: 'Square (512x512)' },
          { value: 'portrait_4_3', label: 'Portrait 4:3' },
          { value: 'portrait_16_9', label: 'Portrait 16:9' },
          { value: 'landscape_4_3', label: 'Landscape 4:3' },
          { value: 'landscape_16_9', label: 'Landscape 16:9' },
        ],
        default: 'landscape_4_3',
      },
      seed: { type: 'integer', label: 'Seed', advanced: true },
      num_images: { type: 'integer', label: 'Number of Images', default: 1, min: 1, max: 4 },
      safety_tolerance: { type: 'enum', label: 'Safety Tolerance', enum: ['1', '2', '3', '4', '5', '6'], default: '2', advanced: true },
    },
    priceHint: '~$0.05 / image',
  },
  {
    id: 'fal-ai/flux-pro/v1.1-ultra',
    provider_id: 'fal',
    label: 'FLUX Pro v1.1 Ultra',
    description: 'Ultra-high-resolution FLUX Pro (up to 4MP)',
    capabilities: ['text2image'],
    params: {
      prompt: { type: 'string', label: 'Prompt', required: true, multiline: true },
      aspect_ratio: {
        type: 'enum',
        label: 'Aspect Ratio',
        enum: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16', '9:21'],
        default: '16:9',
      },
      seed: { type: 'integer', label: 'Seed', advanced: true },
      raw: { type: 'boolean', label: 'Raw Mode', help: 'Generates less processed, more natural-looking images', default: false, advanced: true },
      safety_tolerance: { type: 'enum', label: 'Safety Tolerance', enum: ['1', '2', '3', '4', '5', '6'], default: '2', advanced: true },
    },
    priceHint: '~$0.06 / image',
  },
  {
    id: 'fal-ai/flux-pro/kontext',
    provider_id: 'fal',
    label: 'FLUX Pro Kontext',
    description: 'Context-aware image editing and transformation',
    capabilities: ['image2image'],
    params: {
      prompt: { type: 'string', label: 'Prompt', required: true, multiline: true, help: 'Describe the desired edit' },
      image_url: { type: 'image', label: 'Input Image', required: true },
      seed: { type: 'integer', label: 'Seed', advanced: true },
      guidance_scale: { type: 'number', label: 'Guidance Scale', default: 3.5, min: 1, max: 20, step: 0.5, advanced: true },
      output_format: { type: 'enum', label: 'Output Format', enum: ['jpeg', 'png'], default: 'jpeg', advanced: true },
    },
    priceHint: '~$0.04 / image',
  },
  {
    id: 'fal-ai/flux-2',
    provider_id: 'fal',
    label: 'FLUX.2',
    description: 'Second generation FLUX model',
    capabilities: ['text2image', 'image2image'],
    params: {
      prompt: { type: 'string', label: 'Prompt', required: true, multiline: true },
      image_url: { type: 'image', label: 'Input Image', showWhen: { field: '__capability', value: 'image2image' } },
      strength: { type: 'number', label: 'Strength', default: 0.8, min: 0, max: 1, step: 0.05, showWhen: { field: '__capability', value: 'image2image' } },
      image_size: {
        type: 'enum',
        label: 'Image Size',
        enum: ['square_hd', 'square', 'portrait_4_3', 'portrait_16_9', 'landscape_4_3', 'landscape_16_9'],
        options: [
          { value: 'square_hd', label: 'Square HD (1024x1024)' },
          { value: 'square', label: 'Square (512x512)' },
          { value: 'portrait_4_3', label: 'Portrait 4:3' },
          { value: 'portrait_16_9', label: 'Portrait 16:9' },
          { value: 'landscape_4_3', label: 'Landscape 4:3' },
          { value: 'landscape_16_9', label: 'Landscape 16:9' },
        ],
        default: 'landscape_4_3',
      },
      seed: { type: 'integer', label: 'Seed', advanced: true },
      num_images: { type: 'integer', label: 'Number of Images', default: 1, min: 1, max: 4 },
    },
    priceHint: '~$0.025 / image',
  },

  // ── Image: Other ──────────────────────────────────────────────────
  {
    id: 'fal-ai/ideogram/v3',
    provider_id: 'fal',
    label: 'Ideogram v3',
    description: 'Ideogram v3 via fal.ai - strong typography and design',
    capabilities: ['text2image'],
    params: {
      prompt: { type: 'string', label: 'Prompt', required: true, multiline: true },
      aspect_ratio: {
        type: 'enum',
        label: 'Aspect Ratio',
        enum: ['1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3'],
        default: '1:1',
      },
      style: {
        type: 'enum',
        label: 'Style',
        enum: ['auto', 'general', 'realistic', 'design'],
        default: 'auto',
        advanced: true,
      },
      negative_prompt: { type: 'string', label: 'Negative Prompt', multiline: true, advanced: true },
      seed: { type: 'integer', label: 'Seed', advanced: true },
    },
    priceHint: '~$0.08 / image',
  },
  {
    id: 'fal-ai/recraft/v3/text-to-image',
    provider_id: 'fal',
    label: 'Recraft v3',
    description: 'Recraft v3 via fal.ai - professional vector and raster generation',
    capabilities: ['text2image'],
    params: {
      prompt: { type: 'string', label: 'Prompt', required: true, multiline: true },
      image_size: {
        type: 'enum',
        label: 'Image Size',
        enum: ['square_hd', 'square', 'portrait_4_3', 'portrait_16_9', 'landscape_4_3', 'landscape_16_9'],
        default: 'square_hd',
      },
      style: {
        type: 'enum',
        label: 'Style',
        enum: ['any', 'realistic_image', 'digital_illustration', 'vector_illustration', 'icon'],
        default: 'realistic_image',
      },
      seed: { type: 'integer', label: 'Seed', advanced: true },
    },
    priceHint: '~$0.04 / image',
  },
  {
    id: 'fal-ai/aura-sr',
    provider_id: 'fal',
    label: 'AuraSR',
    description: 'Image upscaler - up to 4x resolution increase',
    capabilities: ['upscale'],
    params: {
      image_url: { type: 'image', label: 'Input Image', required: true },
      upscaling_factor: { type: 'integer', label: 'Upscale Factor', default: 4, min: 2, max: 4, step: 1 },
    },
    priceHint: '~$0.01 / image',
  },

  // ── Video ─────────────────────────────────────────────────────────
  {
    id: 'fal-ai/kling-video/v2.5-turbo/pro/text-to-video',
    provider_id: 'fal',
    label: 'Kling v2.5 Turbo (Text-to-Video)',
    description: 'Kling v2.5 Turbo text-to-video via fal.ai',
    capabilities: ['text2video'],
    params: {
      prompt: { type: 'string', label: 'Prompt', required: true, multiline: true },
      duration: {
        type: 'enum',
        label: 'Duration',
        enum: ['5', '10'],
        options: [
          { value: '5', label: '5 seconds' },
          { value: '10', label: '10 seconds' },
        ],
        default: '5',
      },
      aspect_ratio: {
        type: 'enum',
        label: 'Aspect Ratio',
        enum: ['16:9', '9:16', '1:1'],
        default: '16:9',
      },
      negative_prompt: { type: 'string', label: 'Negative Prompt', multiline: true, advanced: true },
      seed: { type: 'integer', label: 'Seed', advanced: true },
    },
    priceHint: '~$0.14 / 5s',
  },
  {
    id: 'fal-ai/kling-video/v2.5-turbo/pro/image-to-video',
    provider_id: 'fal',
    label: 'Kling v2.5 Turbo (Image-to-Video)',
    description: 'Kling v2.5 Turbo image-to-video via fal.ai',
    capabilities: ['image2video'],
    params: {
      prompt: { type: 'string', label: 'Prompt', required: true, multiline: true },
      image_url: { type: 'image', label: 'Input Image', required: true },
      duration: {
        type: 'enum',
        label: 'Duration',
        enum: ['5', '10'],
        options: [
          { value: '5', label: '5 seconds' },
          { value: '10', label: '10 seconds' },
        ],
        default: '5',
      },
      negative_prompt: { type: 'string', label: 'Negative Prompt', multiline: true, advanced: true },
      seed: { type: 'integer', label: 'Seed', advanced: true },
    },
    priceHint: '~$0.14 / 5s',
  },
  {
    id: 'fal-ai/veo3',
    provider_id: 'fal',
    label: 'Google Veo 3 (Text-to-Video)',
    description: 'Google Veo 3 text-to-video via fal.ai',
    capabilities: ['text2video'],
    params: {
      prompt: { type: 'string', label: 'Prompt', required: true, multiline: true },
      aspect_ratio: {
        type: 'enum',
        label: 'Aspect Ratio',
        enum: ['16:9', '9:16'],
        default: '16:9',
      },
      duration: {
        type: 'enum',
        label: 'Duration',
        enum: ['5', '8'],
        options: [
          { value: '5', label: '5 seconds' },
          { value: '8', label: '8 seconds' },
        ],
        default: '8',
      },
      generate_audio: { type: 'boolean', label: 'Generate Audio', default: true },
      negative_prompt: { type: 'string', label: 'Negative Prompt', multiline: true, advanced: true },
      seed: { type: 'integer', label: 'Seed', advanced: true },
    },
    priceHint: '~$0.50 / video',
  },
  {
    id: 'fal-ai/veo3/image-to-video',
    provider_id: 'fal',
    label: 'Google Veo 3 (Image-to-Video)',
    description: 'Google Veo 3 image-to-video via fal.ai',
    capabilities: ['image2video'],
    params: {
      prompt: { type: 'string', label: 'Prompt', required: true, multiline: true },
      image_url: { type: 'image', label: 'Input Image', required: true },
      aspect_ratio: {
        type: 'enum',
        label: 'Aspect Ratio',
        enum: ['16:9', '9:16'],
        default: '16:9',
      },
      duration: {
        type: 'enum',
        label: 'Duration',
        enum: ['5', '8'],
        options: [
          { value: '5', label: '5 seconds' },
          { value: '8', label: '8 seconds' },
        ],
        default: '8',
      },
      generate_audio: { type: 'boolean', label: 'Generate Audio', default: true },
      seed: { type: 'integer', label: 'Seed', advanced: true },
    },
    priceHint: '~$0.50 / video',
  },
  {
    id: 'fal-ai/wan/v2.2-a14b/text-to-video',
    provider_id: 'fal',
    label: 'Wan v2.2 14B (Text-to-Video)',
    description: 'Wan 2.2 14B text-to-video',
    capabilities: ['text2video'],
    params: {
      prompt: { type: 'string', label: 'Prompt', required: true, multiline: true },
      resolution: {
        type: 'enum',
        label: 'Resolution',
        enum: ['480p', '720p'],
        default: '480p',
      },
      num_frames: { type: 'integer', label: 'Frames', default: 81, min: 17, max: 129, step: 4, advanced: true },
      negative_prompt: { type: 'string', label: 'Negative Prompt', multiline: true, advanced: true },
      seed: { type: 'integer', label: 'Seed', advanced: true },
    },
    priceHint: '~$0.09 / video',
  },
  {
    id: 'fal-ai/wan/v2.2-a14b/image-to-video',
    provider_id: 'fal',
    label: 'Wan v2.2 14B (Image-to-Video)',
    description: 'Wan 2.2 14B image-to-video',
    capabilities: ['image2video'],
    params: {
      prompt: { type: 'string', label: 'Prompt', required: true, multiline: true },
      image_url: { type: 'image', label: 'Input Image', required: true },
      resolution: {
        type: 'enum',
        label: 'Resolution',
        enum: ['480p', '720p'],
        default: '480p',
      },
      num_frames: { type: 'integer', label: 'Frames', default: 81, min: 17, max: 129, step: 4, advanced: true },
      negative_prompt: { type: 'string', label: 'Negative Prompt', multiline: true, advanced: true },
      seed: { type: 'integer', label: 'Seed', advanced: true },
    },
    priceHint: '~$0.09 / video',
  },
  {
    id: 'fal-ai/hunyuan-video',
    provider_id: 'fal',
    label: 'HunyuanVideo',
    description: 'Tencent HunyuanVideo text-to-video',
    capabilities: ['text2video'],
    params: {
      prompt: { type: 'string', label: 'Prompt', required: true, multiline: true },
      resolution: {
        type: 'enum',
        label: 'Resolution',
        enum: ['480p', '720p', '1080p'],
        default: '720p',
      },
      num_frames: { type: 'integer', label: 'Frames', default: 129, min: 45, max: 129, step: 4, advanced: true },
      seed: { type: 'integer', label: 'Seed', advanced: true },
    },
    priceHint: '~$0.11 / video',
  },
  {
    id: 'fal-ai/ltx-2/text-to-video',
    provider_id: 'fal',
    label: 'LTX-Video 2 (Text-to-Video)',
    description: 'Lightricks LTX-Video 2 text-to-video',
    capabilities: ['text2video'],
    params: {
      prompt: { type: 'string', label: 'Prompt', required: true, multiline: true },
      resolution: {
        type: 'enum',
        label: 'Resolution',
        enum: ['480p', '720p'],
        default: '480p',
      },
      num_frames: { type: 'integer', label: 'Frames', default: 97, min: 17, max: 161, step: 8, advanced: true },
      negative_prompt: { type: 'string', label: 'Negative Prompt', multiline: true, advanced: true },
      seed: { type: 'integer', label: 'Seed', advanced: true },
    },
    priceHint: '~$0.03 / video',
  },
];
